baseURL: "https://jchgu.rbind.io" 
title: Jiancheng Gu
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

#menu:
#    main:
#        - name: Books
#          url: books/
#          weight: 5 
#        - name: Papers
#          url: papers/
#          weight: 2
#        - name: Courses
#          url: courses/
#          weight: 3
#        - name: Data
#          url: data/
#          weight: 4 
#        - name: Blog
#          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
#          weight: 6

params:
    description: "PhD Researcher in Migration Studies"
    author: Jiancheng Gu
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    #MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jiancheng Gu
          subtitle: 
            "Welcome!
            I am a PhD candidate and researcher at the 
            [Universität für Weiterbildung Krems](https://www.donau-uni.ac.at/en/), Austria. 
            I evaluate migration policy using quantitative methods. 
            Specifically, I study how countries negotiate and implement return policies targeting unauthorized migrants. 
            My dissertation contributes to two Horizon Europe projects: 
            [Finding Agreement in Return (FAiR)](https://fair-return.org) and
            [Measuring Irregular Migration (MIrreM)](https://irregularmigration.eu/).
            "
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Jiancheng Gu (Photo©Daniel Novotny)
          buttons:
                  - name: "Resources"
                    url: resources/
#           - name: FAiR Project
#              url: https://fair-return.org


    socialIcons:
        - name: Email
          url: mailto:jiancheng.gu@donau-uni.ac.at
        - name: CV
          url: cv.pdf
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=q4IU8RYAAAAJ
        - name: orcid
          url: https://orcid.org/0009-0002-3033-6472
        - name: GitHub
          url: https://github.com/jchgu
        - name: bluesky
          url: https://bsky.app/profile/jchgu.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jiancheng Gu"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2